### ISSUE TITLE
Unfollow following list

### ISSUE THREAD

**Issue by alinzm** [SabujXi/LinkedIn-Bulk-Invitation-Withdraw-Script#1]
Hey Man,

Thanks for your great code, do you think is there a way to write the similar code for unfollow the following from this page: https://www.linkedin.com/feed/following/

Best

**Comment by SabujXi** [comment]
I will take a look at it and I will let you know. It will be better if you can send me an email on this, so that I can add that to my to-do list. (email address is available on my website home page)
